# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

# count variables
nfs = 9 # Faker standard members
nfp = 3 # Faker premium members
nw = 27 # wikis
pws = ['fdsjkl']

# several members are first created manually with a simple password for testing
User.create!(
  email: 'ed@example.com',
  password: pws[0],
  confirmed_at: Time.now
)

User.create!(
  email: 'ben@example.com',
  password: pws[0],
  confirmed_at: Time.now,
  role: 'premium'
)

User.create!(
  email: 'ron@example.com',
  password: pws[0],
  confirmed_at: Time.now,
  role: 'premium'
)

User.create!(
  email: 'casey@example.com',
  password: pws[0],
  confirmed_at: Time.now,
  role: 'admin'
)

# additional standard and premium members are generated by Faker
nfs.times do
  pws.push(Faker::Internet.password)
  User.create!(
    email: Faker::Internet.safe_email,
    password: pws.last,
    confirmed_at: Time.now
  )
end

nfp.times do
  pws.push(Faker::Internet.password)
  User.create!(
    email: Faker::Internet.safe_email,
    password: pws.last,
    role: 'premium',
    confirmed_at: Time.now
  )
end

users = User.all

# wikis are generated, some private
nw.times do
  wiki_user = users.sample
  wiki_private = false
  
  # if authorized, with 1/3 probability assign wiki as private
  unless User.find(wiki_user.id).standard?
    wiki_private = [false,false,true].sample
  end
  
  Wiki.create!(
    user: wiki_user,
    title: Faker::Lorem.sentence,
    body: Faker::Lorem.paragraph,
    private: wiki_private
  )
end

puts "Seed finished"
puts "#{User.count} users created:"
puts "  #{nfs+1} standard"
puts "  #{User.where(role: :premium).count} premium"
puts "  1 admin"
puts "#{nw} wikis created:"
puts "  #{Wiki.where(private: true).count} private"

File.open("pws.txt","w") do |newFile|
  newFile.puts( pws.join("\n") )
end
