# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

# count variables
ns = 9 # Faker standard members
np = 3 # Faker premium members
na = 1 # Faker admin members
nw = 48 # wikis

# 1 of each kind of member is created with a known password
User.create!(
  email: 'aldo@in1.io',
  password: 'fdsjkl',
  confirmed_at: Time.now
)

User.create!(
  email: 'ben@in2.io',
  password: 'fdsjkl',
  confirmed_at: Time.now,
  role: 'premium'
)

User.create!(
  email: 'casey@in3.io',
  password: 'fdsjkl',
  confirmed_at: Time.now,
  role: 'admin'
)

# additional members are generated by Faker
ns.times do
  User.create!(
    email: Faker::Internet.safe_email,
    password: Faker::Internet.password,
    confirmed_at: Time.now
  )
end

np.times do
  User.create!(
    email: Faker::Internet.safe_email,
    password: Faker::Internet.password,
    role: 'premium',
    confirmed_at: Time.now
  )
end

na.times do
  User.create!(
      email: Faker::Internet.safe_email,
      password: Faker::Internet.password,
      role: 'admin',
      confirmed_at: Time.now
  )
end

users = User.all

nw.times do
  Wiki.create!(
    user: users.sample,
    title: Faker::Lorem.sentence,
    body: Faker::Lorem.paragraph
  )
end

puts "Seed finished"
puts "#{User.count} users created:"
puts "  #{ns+1} standard"
puts "  #{np+1} premium"
puts "  #{na+1} admin"
puts "#{nw} wikis created"
